### 1. 토큰 확인
POST {{host}}/auth/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### 2. 토큰 인증 테스트
POST {{host}}/test
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

